(defun indentation()
  (interactive)
  (let ((initial-mode major-mode))
    (if (not (use-region-p))
	(indent-according-to-mode)
      (sgml-mode)
      (indent-region (region-beginning) (region-end))
      (funcall initial-mode))))

(defun rng-find-error()
  (interactive)
  (when (eq (rng-previous-error 1) nil)
    (rng-next-error 1)))

(defun validate()
  (interactive)
  (sgml-validate (concat "onsgmls -w xml -s -E30000 -f /home/oswoboda/temp.txt -D /home/journal/Journal-base/lib/xml/ " (buffer-name) " ; grep -v 'Nicht\-SGML\-Zeichen' /home/oswoboda/temp.txt")))

(defun html-local-keymap()
  (local-set-key (kbd "\C-c\C-v") 'validate)
  (local-set-key (kbd "\C-c\C-n") 'rng-find-error)
  (local-set-key (kbd "C-c v") 'rng-validate-mode)
  (local-set-key (kbd "TAB") 'indentation)
  (setq line-number-display-limit nil)
  (setq paragraph-start "\f\\|[ 	]*$")
  (setq paragraph-seperate "[ 	\f]*$")
  (rng-validate-mode)
  )

(add-hook 'html-mode-hook 'html-local-keymap)