;; default
(set-foreground-color "#f8f8f2")
(set-background-color "#000000")
(set-cursor-color "#f8f8f0")
(set-face-foreground 'font-lock-comment-face "#95917E")
(set-face-foreground 'font-lock-string-face "#e6db74")
(set-face-foreground 'font-lock-keyword-face "#F92672")
(set-face-foreground 'font-lock-function-name-face "#A6E22E")
(set-face-foreground 'font-lock-variable-name-face "#98fbff")
(set-face-foreground 'font-lock-type-face "#A6E22E")
(set-face-foreground 'region "#272822")
(set-face-background 'region "#66D9EF")
(set-face-foreground 'font-lock-constant-face "#66d9ef")
(custom-set-faces
 '(mode-line ((((class color) (min-colors 88)) (:background "black" :foreground "grey" :box (:line-width 1 :color "grey" :style released-button)))))
 '(rng-error ((t (:height 130 :foreground "#ff0000" :underline t))))
 '(scroll-bar ((t (:background "black"))))
 '(fringe ((((class color) (background dark)) (:background "black"))))
)
